# Generated by Django 3.2.4 on 2021-06-22 15:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=99, null=True)),
                ('founder_name', models.CharField(blank=True, max_length=99, null=True)),
                ('refrence_number', models.CharField(blank=True, max_length=99, null=True)),
                ('address', models.CharField(blank=True, max_length=99, null=True)),
                ('is_working', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('total_fund_raise', models.CharField(blank=True, max_length=99, null=True)),
                ('slug', models.CharField(max_length=130)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=99, null=True)),
                ('last_name', models.CharField(blank=True, max_length=99, null=True)),
                ('address', models.CharField(blank=True, max_length=99, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('experiance', models.IntegerField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee', to='companyapp.company')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
